export { default as carousel_1 } from "./carousel-1.jpg"
export { default as carousel_2 } from "./carousel-2.jpg"
export { default as carousel_3 } from "./carousel-3.jpg"
export { default as dummy } from "./dummy.png"
export { default as model } from "./model.jpg"
export { default as user } from "./user.jpg"
