export { default as carousel_1 } from "./carousel-1.webp"
export { default as carousel_2 } from "./carousel-2.webp"
export { default as carousel_3 } from "./carousel-3.webp"
export { default as olonagirl_crest } from "./olonagirl-crest.png"
export { default as olonagirl_dark } from "./olonagirl_dark.png"
export { default as olonagirl_light } from "./olonagirl_light.png"
export { default as user } from "./user.jpg"
