export const SizeGuideData = [
	{ ukSize: 2, usSize: "00", euSize: 30, intl: "xxs" },
	{ ukSize: 4, usSize: 0, euSize: 32, intl: "xs" },
	{ ukSize: 6, usSize: 2, euSize: 34, intl: "xs" },
	{ ukSize: 8, usSize: 4, euSize: 36, intl: "s" },
	{ ukSize: 10, usSize: 6, euSize: 38, intl: "s" },
	{ ukSize: 12, usSize: 8, euSize: 40, intl: "m" },
	{ ukSize: 14, usSize: 10, euSize: 42, intl: "m" },
	{ ukSize: 16, usSize: 12, euSize: 44, intl: "l" },
	{ ukSize: 18, usSize: 14, euSize: 46, intl: "l" },
	{ ukSize: 20, usSize: 16, euSize: 48, intl: "xl" },
	{ ukSize: 22, usSize: 18, euSize: 50, intl: "xl" },
	{ ukSize: 24, usSize: 20, euSize: 52, intl: "xxl" },
	{ ukSize: 26, usSize: 22, euSize: 54, intl: "xxl" },
]
